version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`hscb.online`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  directus:
    image: directus/directus:11.1.1
    restart: always
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    environment:
      KEY: "b3f3b924-4f27-4a0b-9d2a-874591a27e02"
      SECRET: "e1a9b3a0-f8f4-4c57-89df-1d54e0c4b223"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      ADMIN_EMAIL: "admin@demo.com"
      ADMIN_PASSWORD: "321456"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS"
      PUBLIC_URL: "https://api.hscb.online"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directus.rule=Host(`api.hscb.online`)"
      - "traefik.http.services.directus.loadbalancer.server.port=8055"

volumes:
  directus_database:
  directus_uploads:
  directus_extensions:
